# Generated by Django 6.0.2 on 2026-02-25 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.FloatField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.lessongroup')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.FloatField()),
                ('slide_type', models.CharField(choices=[('Intro', 'Intro'), ('MediaIntro', 'MediaIntro'), ('MultipleChoice', 'MultipleChoice'), ('TrueFalse', 'TrueFalse'), ('BuildBlock', 'BuildBlock'), ('FillInBlank', 'FillInBlank'), ('MatchPairs', 'MatchPairs'), ('TypeWord', 'TypeWord'), ('Crossword', 'Crossword'), ('ToneMarking', 'ToneMarking'), ('Speaking', 'Speaking'), ('Sketch', 'Sketch'), ('TextResponse', 'TextResponse'), ('ReadParagraph', 'ReadParagraph')], max_length=50)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='curriculum.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FillInBlankContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blanks', models.JSONField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.sentence')),
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fib_content', to='curriculum.lessonslide')),
            ],
        ),
        migrations.CreateModel(
            name='BuildBlockContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_order', models.JSONField(blank=True, null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.sentence')),
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bb_content', to='curriculum.lessonslide')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to='media/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mc_content', to='curriculum.lessonslide')),
            ],
        ),
        migrations.CreateModel(
            name='SlidePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(blank=True, null=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.phrase')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_phrases', to='curriculum.lessonslide')),
            ],
        ),
        migrations.CreateModel(
            name='SlideSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(blank=True, null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.sentence')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_sentences', to='curriculum.lessonslide')),
            ],
        ),
        migrations.CreateModel(
            name='SlideWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(blank=True, null=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_words', to='curriculum.lessonslide')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.word')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tf_content', to='curriculum.lessonslide')),
            ],
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_groups', to='curriculum.unit'),
        ),
    ]
