# Generated by Django 6.0.2 on 2026-02-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('curriculum', '0001_initial'),
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildblockcontent',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.sentence'),
        ),
        migrations.AddField(
            model_name='fillinblankcontent',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.sentence'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.lessongroup'),
        ),
        migrations.AddField(
            model_name='lessonslide',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='fillinblankcontent',
            name='slide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fib_content', to='curriculum.lessonslide'),
        ),
        migrations.AddField(
            model_name='buildblockcontent',
            name='slide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bb_content', to='curriculum.lessonslide'),
        ),
        migrations.AddField(
            model_name='media',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='multiplechoicecontent',
            name='slide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mc_content', to='curriculum.lessonslide'),
        ),
        migrations.AddField(
            model_name='slidephrase',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.phrase'),
        ),
        migrations.AddField(
            model_name='slidephrase',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_phrases', to='curriculum.lessonslide'),
        ),
        migrations.AddField(
            model_name='slidesentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.sentence'),
        ),
        migrations.AddField(
            model_name='slidesentence',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_sentences', to='curriculum.lessonslide'),
        ),
        migrations.AddField(
            model_name='slideword',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_words', to='curriculum.lessonslide'),
        ),
        migrations.AddField(
            model_name='slideword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.word'),
        ),
        migrations.AddField(
            model_name='truefalsecontent',
            name='slide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tf_content', to='curriculum.lessonslide'),
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_groups', to='curriculum.unit'),
        ),
    ]
