# Generated by Django 6.0.2 on 2026-03-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_lessonslide_title_lesson_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code',
            field=models.CharField(default='902100', editable=False, max_length=6),
        ),
    ]
