# Generated by Django 6.0.2 on 2026-03-11 03:10

import apps.curriculum.models.lesson
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_lesson_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='code',
            field=models.CharField(default=apps.curriculum.models.lesson.generate_unique_short_code, editable=False, max_length=6, unique=True),
        ),
    ]
