# Generated by Django 6.0.5 on 2026-05-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_type', models.CharField(choices=[('Intro', 'Intro'), ('MultipleChoice', 'MultipleChoice'), ('TrueFalse', 'TrueFalse'), ('BuildBlock', 'BuildBlock'), ('FillInBlank', 'FillInBlank'), ('MatchPairs', 'MatchPairs'), ('TypeWord', 'TypeWord'), ('Crossword', 'Crossword'), ('ToneMarking', 'ToneMarking'), ('Speaking', 'Speaking'), ('Sketch', 'Sketch'), ('TextResponse', 'TextResponse'), ('ReadParagraph', 'ReadParagraph'), ('Random', 'Random')], default='Intro', max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
