# Generated by Django 6.0.2 on 2026-03-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userlessonprogress_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLessonProgress',
        ),
    ]
