# Generated by Django 6.0.2 on 2026-03-11 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_userlessonprogress'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
