# Generated by Django 6.0.2 on 2026-03-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_userwordprogress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='started_at',
        ),
    ]
