# Generated by Django 6.0.5 on 2026-05-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_text', models.CharField(max_length=255)),
                ('normalized_text', models.TextField(db_index=True)),
                ('construction_type', models.CharField(choices=[('Idiom', 'Idiom'), ('pattern', 'Pattern'), ('Phrase', 'Phrase'), ('Sentence', 'Sentence')], max_length=255)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], db_index=True, default=1)),
                ('is_reviewable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=255)),
                ('normalized_lemma', models.CharField(max_length=255)),
                ('tone_pattern', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LexemeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vocabulary.lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('grammatical_role', models.CharField(blank=True, max_length=50)),
                ('highlight_start', models.PositiveIntegerField(blank=True, null=True)),
                ('highlight_end', models.PositiveIntegerField(blank=True, null=True)),
                ('child_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.construction')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='vocabulary.construction')),
                ('lexeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.lexemevariant')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_direct', models.BooleanField(default=True)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexeme_index', to='vocabulary.construction')),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.lexeme')),
            ],
            options={
                'indexes': [models.Index(fields=['lexeme'], name='vocabulary__lexeme__80e4f1_idx'), models.Index(fields=['construction'], name='vocabulary__constru_07dcd7_idx')],
                'unique_together': {('construction', 'lexeme', 'depth')},
            },
        ),
    ]
