# Generated by Django 6.0.2 on 2026-03-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencecomponent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'grammar'), ('model__in', ['word', 'phrase'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
