# Generated by Django 6.0.2 on 2026-03-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0002_alter_sentencecomponent_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentencecomponent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='sentencecomponent',
            name='object_id',
        ),
        migrations.AddField(
            model_name='sentencecomponent',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grammar.phrase'),
        ),
        migrations.AddField(
            model_name='sentencecomponent',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grammar.word'),
        ),
    ]
