# Generated by Django 6.0.2 on 2026-03-10 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0003_remove_sentencecomponent_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='is_idiom',
            field=models.BooleanField(default=False, help_text='Check if this phrase is a true idiom (non-literal translation)'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='difficulty',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='word',
            name='related_words',
            field=models.ManyToManyField(blank=True, to='grammar.word'),
        ),
        migrations.CreateModel(
            name='SentenceWordIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_words', to='grammar.sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_occurrences', to='grammar.word')),
            ],
            options={
                'indexes': [models.Index(fields=['word'], name='grammar_sen_word_id_2b80d7_idx'), models.Index(fields=['sentence'], name='grammar_sen_sentenc_952eb0_idx')],
                'unique_together': {('sentence', 'word')},
            },
        ),
    ]
