# Generated by Django 6.0.2 on 2026-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0004_phrase_is_idiom_sentence_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('particle', 'Particle'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('question', 'Question')], max_length=50, null=True),
        ),
    ]
